#!/bin/bash

get_pwr() {
    PWR=$(upower -i $(power -e) | grep BAT) | grep "state" | sed s:'Battery is'::
}

get_pwr

if [ $PWR == discharging ]; then
    text="󰾅"
    tooltip="Discharging"
elif [ $PWR == Performance ]; then
    text="󰓅"
    tooltip="Performance"
elif [ $PWR == Quiet ]; then
    text="󰾆"
    tooltip="Quiet"
fi

echo '{"text": "'$text'", "tooltip": "'$tooltip'"}'

if [[ "$1" == "next" ]]; then
    asusctl profile -n; pkill -SIGRTMIN+8 waybar
    get_pwr
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "$PWR Power Profile"
fi